### ISSUE TITLE
Error Installing on BG2EE

### ISSUE THREAD

**Issue by neuroghast** [11jo/PlanarSphere#6]
Tried to install this mod and got this error:

`ERROR: Unix.Unix_error(20, "stat", "dialog.tlk")
`

I've attached my weidu and the debug file (had to change the extension to .txt so I could drop it here, but I imagine it's still fully readable).

Additional info: 
- installed the latest release avaliable, v26c 
- it's a regular EE version, no EET or anything like that.

Let me know if I can provide any more info to help!

[WeiDU.log](https://github.com/user-attachments/files/18143560/WeiDU.log)
[SETUP-PLANARSPHEREMOD.txt](https://github.com/user-attachments/files/18143562/SETUP-PLANARSPHEREMOD.txt)

**Comment by 11jo** [comment]
Hello, the release is the last version from SHS.

You need to use the master for installing the mod on EE.

Don't hesitate to provide feedback.

**Comment by neuroghast** [comment]
Ok, it works now. Thanks for the quick reply!

**Comment by neuroghast** [comment]
Installing the correct version didn't result in any issue.
